### ISSUE TITLE
requirements.txt missing libraries

### ISSUE THREAD

**Issue by Chrisini** [DIAGNijmegen/picai_baseline#17]
missing:
pip install torch 
pip install threadpoolctl 
pip install batchgenerators
pip install monai
pip install tensorboard

**Comment by joeranbosma** [comment]
Hi @Chrisini,

It seems you missed the [U-Net specific requirements.txt](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/unet/requirements.txt). The general requirements.txt are just to enable the scripts (i.e., data preprocessing). The different baseline models have their own training environments and requirements.

**Comment by joeranbosma** [comment]
Hi @Chrisini, did this solve your issue?

**Comment by joeranbosma** [comment]
Hi @Chrisini, I am assuming it did. Please re-open this issue if you still have problems.
