### ISSUE TITLE
nndet_generate_detection_maps.py memory problems

### ISSUE THREAD

**Issue by brambozz** [DIAGNijmegen/picai_baseline#23]
The [nndet_generate_detection_maps.py](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/nndetection/training_docker/nndet_generate_detection_maps.py) failed for me a few times, even when using a node with 32 GB RAM. For me, commenting out [line 113](https://github.com/DIAGNijmegen/picai_baseline/blob/09fa165b0499b4262fc9aed6ca7e8670a8a5fc16/src/picai_baseline/nndetection/training_docker/nndet_generate_detection_maps.py#L113) fixes this. This line saves the detection map for each case, leading to a slowly filling RAM. Is there a reason detection maps are saved in RAM and returned? (they are not used in this script directly)

**Comment by joeranbosma** [comment]
Thanks for raising this issue! There is no reason why the detection maps should always be returned. 

I've made a flag to disable this behaviour in https://github.com/DIAGNijmegen/picai_baseline/commit/35f120fcb843d1aa842a484002b8c8cf0eddd7a9. By default it will keep collecting the detection maps, to allow others who have incorporated this function in their workflow to keep using it in the same way.

However, setting [`return_detection_maps=False`](https://github.com/DIAGNijmegen/picai_baseline/blob/35f120fcb843d1aa842a484002b8c8cf0eddd7a9/src/picai_baseline/nndetection/training_docker/nndet_generate_detection_maps.py#L146) will now prevent collecting the detection maps, and therefore the high RAM requirements.
