### ISSUE TITLE
Wrong focal loss in unet training.

### ISSUE THREAD

**Issue by quqixun** [DIAGNijmegen/picai_baseline#24]
As lines [#35](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/unet/training_setup/loss_functions/focal.py#L35) and [#39](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/unet/training_setup/loss_functions/focal.py#L39) in [focal.py](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/unet/training_setup/loss_functions/focal.py), only the last sample is used to calculate focal loss, because the first channel is batch size.
However, as the description in [unet readme](https://github.com/DIAGNijmegen/picai_baseline/blob/main/unet_baseline.md) and [train.py](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/unet/train.py), there are 8 samples in a batch.
Thus, not all samples are used to calculate focal loss.

**Comment by anindox8** [comment]
Thanks for spotting this! Fixed with [commit 564ca46](https://github.com/DIAGNijmegen/picai_baseline/commit/564ca4698416e3a2b905bd80226b47f90616360a).
