### ISSUE TITLE
which data dir as the input dir we should use for inference 

### ISSUE THREAD

**Issue by Chacha-Chen** [DIAGNijmegen/picai_baseline#27]
Hi, I am following the instruction provided to train the nnUnet. For inference, there is an arg  `--input input/images`. Which directory we should use? raw data or preprocessed or cropped? 

```
docker run --cpus=8 --memory=28gb --gpus='"device=0"' --rm \
    -v /path/to/test_set/images:/input/images \
    -v /path/to/workdir/results:/workdir/results \
    -v /path/to/workdir/predictions:/output/predictions \
    joeranbosma/picai_nnunet:latest nnunet predict Task2201_picai_baseline \
    --trainer nnUNetTrainerV2_Loss_FL_and_CE_checkpoints \
    --fold 0 --checkpoint model_best \
    --results /workdir/results \
    --input /input/images/ \
    --output /output/predictions \
    --store_probability_maps
```

Thanks!

**Comment by joeranbosma** [comment]
Hi, I missed this question initially. Hopefully, you were able to figure it out.
You would use the nnU-Net Raw Archive format as input (called `nnUNet_raw_data` most likely).
Please re-open this issue if you need further information.
