### ISSUE TITLE
wrong path to labels when running preprocessing with prepare_data.py

### ISSUE THREAD

**Issue by PaWeRe** [DIAGNijmegen/picai_baseline#43]
Hi,

it seems that the path to the labels '/input/labels/' described in the repo, does not correspond to the expected input path in the picai_archive.py, defined in the prepare_data.py script '/input/picai_labels/' (and passed in the 'mha2nnunet_settings_path' function as 'annotations_dir').  When running the docker command for data preprocessing (converting from mha to the nnU-Net Raw Data Archive) this leads to the 'all_scans_found' not being assigned and hence the error message "Did not find any MHA scans in {archive_dir}, {archive_list} {all_scans_found} aborting."

I solved the issue by deleting the "labels" folder and directly putting the subfolder "picai_labels" into the input folder. An easy general fix would be to update the description of the folder structure in the picai_baseline repo (from "labels" to "picai_labels") and change the cloning command of the picai_labels to "git clone https://github.com/DIAGNijmegen/picai_labels /input/".

Best,

Patrick

**Comment by joeranbosma** [comment]
Hi @PaWeRe,
Thanks for pointing out this issue! I've incorporated these changes in https://github.com/DIAGNijmegen/picai_baseline/pull/44, could you check if these are the changes you intended?

Thanks,
Joeran

**Comment by PaWeRe** [comment]
Hi @joeranbosma,
I left a comment in #44!

Best,
Patrick
