### ISSUE TITLE
No encoding for DataFrame.to_excel()

### ISSUE THREAD

**Issue by loki-veera** [DIAGNijmegen/picai_baseline#47]
https://github.com/DIAGNijmegen/picai_baseline/blob/b3d6d0f3d742945caf3f95173d80e32a7145d1dc/src/picai_baseline/unet/training_setup/callbacks.py#L213

Dear authors, 

When training UNet, I encountered error no encoding in pandas dataframe.to_excel function.

**Comment by joeranbosma** [comment]
Hi @loki-veera,

Thanks for raising this issue! Apparently, the `encoding='utf-8'` part needs to be removed now. I'll update the baseline code to reflect this update.

Best,
Joeran
