### ISSUE TITLE
AttributeError in MultiThreadedAugmenter during UNet training.

### ISSUE THREAD

**Issue by buraknebio** [DIAGNijmegen/picai_baseline#54]
Hello,
I am encountering an AttributeError in my semi-supervised UNet training setup. Initially, I consistently received the error in every epoch. After updating my WSL RAM to 16GB, the error persists but now occurs on different number of epochs.

I am using this command on ubuntu terminal:

```python
python3 -u train.py   --weights_dir='/home/buraknebio/picai_baseline/workdir/results/UNet/weights/'  
 --overviews_dir='/home/buraknebio/picai_baseline/workdir/results/UNet/overviews/Task2201_picai_baseline'  
 --folds 0 1 2 3 4 --max_threads 6 --enable_da 1 --num_epochs 250   --validate_n_epochs 1 --validate_min_epoch 0
 ```

### Error Details:

```
Epoch 59/250 (Train. Loss: 11120.5093; Time: 99sec; Steps Completed: 100)
Valid. Performance [Benign or Indolent PCa (n=37) vs. csPCa (n=19)]:
Ranking Score = 0.456, AP = 0.240, AUROC = 0.673
Traceback (most recent call last):
  File "/home/buraknebio/picai_baseline/src/picai_baseline/unet/train.py", line 161, in <module>
    main()
  File "/home/buraknebio/picai_baseline/src/picai_baseline/unet/train.py", line 134, in main
    model, optimizer, train_gen, tracking_metrics, writer = optimize_model(
  File "/home/buraknebio/.local/lib/python3.10/site-packages/picai_baseline/unet/training_setup/callbacks.py", line 111, in optimize_model
    for batch_data in train_gen:
  File "/home/buraknebio/.local/lib/python3.10/site-packages/picai_baseline/unet/training_setup/augmentations/multi_threaded_augmenter.py", line 200, in __next__
    item = self.__get_next_item()
  File "/home/buraknebio/.local/lib/python3.10/site-packages/picai_baseline/unet/training_setup/augmentations/multi_threaded_augmenter.py", line 188, in __get_next_item
    if not self.pin_memory_queue.empty():
AttributeError: 'MultiThreadedAugmenter' object has no attribute 'pin_memory_queue'. Did you mean: 'pin_memory_thread'?
```

### Iterative Training Attempts

Due to the recurring AttributeError and the inconsistency in the number of epochs at which it occurs, I've attempted to mitigate the issue by running the training script in a loop for several iterations. Each iteration involves restarting the training process from the beginning, utilizing the weights of the previous epoch. 

epoch | train_loss | valid_auroc | valid_ap | valid_ranking
-- | -- | -- | -- | --
101 | 7638,408 | 0,607397 | 0,256964 | 0,43218
102 | 8185,666 | 0,600284 | 0,290952 | 0,445618
103 | 8492,908 | 0,611664 | 0,259046 | 0,435355
104 | 8340,153 | 0,620199 | 0,255093 | 0,437646
48 | 11815,43 | 0,657183 | 0,22646 | 0,441822
49 | 11887,91 | 0,577525 | 0,213911 | 0,395718
50 | 14961,47 | 0,608819 | 0,226688 | 0,417754

As it turned out, I got an error on the epoch #104, and in that iteration weights went back to the beginning, and continued from epoch #48.

Unfortunately, while this approach allows the script to continue running and avoids termination, it appears to consistently revert to a specific epoch in each iteration. This behavior raises concerns about the progress of the training and the accurate updating of weights. I am seeking guidance on how to address this issue.

### Environment Details:
OS: WSL Ubuntu 2
Python Version: 3.10.12
GPU: RTX 4060 8GB
Processor: AMD Ryzen 5 5600
RAM: 16GB (100% allocated to WSL)
```               
               total        used        free      shared  buff/cache   available
Mem:            15Gi       482Mi        10Gi       2.0Mi       4.7Gi        14Gi
Swap:          4.0Gi        33Mi       4.0Gi
```

**Comment by Jefferyy-Peng** [comment]
Hi, I think I have the same issue with you. After debugging the problem was at the Resize transformation in monai. If you create a breakpoint at where the __call__ function of Resize, you will see that the transform calls the torch's interpolation function which seems not compatible with author's multithreading protocol I guess. I can't do further debugging because the torch function calls a c function which I can't trace. Hope this information could help.

**Comment by Jefferyy-Peng** [comment]
Hi @anindox8, the thread you referred to uses your docker image. But I'm not using your docker image so the memory size should not be the problem I suppose. Do you have any other suggestions?

**Comment by Jefferyy-Peng** [comment]
After I comment out `    check_loader = DataLoaderFromDataset(check_ds, batch_size=args.batch_size, num_threads=args.num_threads)
    data_pair = monai.utils.misc.first(check_loader)
    print('DataLoader - Image Shape: ', data_pair['data'].shape)
    print('DataLoader - Label Shape: ', data_pair['seg'].shape)
    print("-"*100)

    assert args.image_shape == list(data_pair['data'].shape[2:])
    assert args.num_channels == data_pair['data'].shape[1]
    assert args.num_classes == len(np.unique(train_json['case_label']))` in the data_generator.py[https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/unet/training_setup/data_generator.py](url), I'm able to run the code. I'm very curious why this is the case?

**Comment by joeranbosma** [comment]
Closing as stale. Feel free to reopen if still relevant, @Jefferyy-Peng or @anindox8.
