### ISSUE TITLE
Overfitting Issue with PICAI Baseline Model nnDetection

### ISSUE THREAD

**Issue by CollapsarEcho** [DIAGNijmegen/picai_baseline#57]
Dear PICAI team,

Recently, I have been working with the baseline model provided for the PICAI dataset. Although I carefully followed the instructions, I keep encountering significant overfitting issues. Attached, you can find a plot illustrating the training process.

![image](https://github.com/user-attachments/assets/8fb9602a-bd9b-4325-b77b-351956a3924d)

I’m wondering if there might be an issue with my training environment, or if there are adjustments I should consider making to the trainer.

Here are some details about my setup:

- Training environment: Official picai_baseline Docker on A100 40GB
- Cross-validation: Custom stratified 5-fold CV
- Preprocessing: I used prepare_data.py and obtained 1295 cases, 80% of which were used in the 5-fold CV to train the model.

Thank you in advance for your assistance, and I hope you’re having a great summer!

**Comment by joeranbosma** [comment]
Dear @CollapsarEcho,

For the PI-CAI baseline, we haven't made any adjustments to the parameters of the nnDetection framework, so it seems your setup is correct. To verify this, I visualized the mAP@0.1,0.5,0.05 metric for the first fold of the [nnDetection (supervised)](https://grand-challenge.org/algorithms/the-pi-cai-challenge-baseline-nndetection/) algorithm, which should closely match your implementation.

![mAP Visualization](https://github.com/user-attachments/assets/f79bfba2-ae0a-4ddc-bd2c-dac4fd18e2bd)

The graph looks very similar, suggesting that you've implemented the baseline correctly, and we both observe overfitting occurring quite quickly.

We noticed a significant performance improvement when incorporating the AI-derived annotations (to train the [semi-supervised nnDetection](https://grand-challenge.org/algorithms/pi-cai-baseline-nndetection-semi-supervised/)). However, overfitting still seems to persist:

![Performance with AI-derived Annotations](https://github.com/user-attachments/assets/1ff7aa6d-f9fa-41f5-b265-2cc8c023fc17)

I think if you're able to combat the overfitting issue, that could lead to improved performance! I don't have any leads in this direction, unfortunately.

All the best,
Joeran

**Comment by CollapsarEcho** [comment]
Thank you for your response! I’m glad to hear that I was on the right track with the reproduction. I’ll definitely explore some additional methods to address the issue. Additional institutional datasets seem like a promising approach, I'll give that a try.
