### ISSUE TITLE
How to use the semi-supervised baseline?

### ISSUE THREAD

**Issue by Kyfafyd** [DIAGNijmegen/picai_baseline#8]

**Comment by joeranbosma** [comment]
Hi @Kyfafyd,

The semi-supervised models are trained in a very similar manner as the supervised models. To train the semi-supervised models, you can prepare the dataset using [prepare_data_semi_supervised.py](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/prepare_data_semi_supervised.py). See [Data Preprocessing](https://github.com/DIAGNijmegen/picai_baseline/blob/main/README.md#data-preprocessing) for details. Then, follow the supervised steps, replacing Task2201_picai_baseline with Task2203_picai_baseline.

I've also added this to the nnU-Net and nnDetection instructions now.

Does this make it sufficiently clear?

Kind regards,
Joearn

**Comment by Kyfafyd** [comment]
Hi, @joeranbosma 
Thanks for your further clarification!
I am now trying to run [prepare_data_semi_supervised.py](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/prepare_data_semi_supervised.py), but always get 
```
Processed 1458 items, with -42 cases skipped and 42 errors. 

Did not generate dataset.json, as only 1458/1500 items are converted successfully. 
```
I have checked the log and found some images meet the following error, can you help me figure this out?
```
00009 10009/1000009
Unexpected error: Exception thrown in SimpleITK ResampleImageFilter_Execute: /tmp/SimpleITK-build/ITK/Modules/Core/Common/src/itkPlatformMultiThreader.cxx:238:
ITK ERROR: PlatformMultiThreader(0x7f97f8019df0): Exception occurred during SingleMethodExecute
/tmp/SimpleITK-build/ITK/Modules/Core/Common/src/itkPlatformMultiThreaderPosix.cxx:189:
ITK ERROR: PlatformMultiThreader(0x7f97f8019df0): Unable to join thread.
```
BTW, I just uncomment these two lines:
```python
mha2nnunet_settings["preprocessing"]["matrix_size"] = [20, 256, 256]
mha2nnunet_settings["preprocessing"]["spacing"] = [3.0, 0.5, 0.5]
```

**Comment by joeranbosma** [comment]
```bash
conda create --name picai_prep python=3.10
conda activate picai_prep
pip install picai_prep
unzip picai_public_images_fold0.zip -d /input/images/
```

**Comment by Kyfafyd** [comment]
Hi, @joeranbosma 
I am using Linux.

**Comment by Kyfafyd** [comment]
Hi, what is this meaning?

Best,
Zhao

**Comment by Kyfafyd** [comment]
Hi, @joeranbosma 
Thanks very much for the update,
After reinstall picai_prep, I meet the following error:
```
Traceback (most recent call last):
  File "src/picai_baseline/prepare_data_semi_supervised.py", line 121, in <module>
    archive = MHA2nnUNetConverter(
TypeError: __init__() got an unexpected keyword argument 'input_path'
```

**Comment by joeranbosma** [comment]
Apologies, we changed the signature. Could you change the variable names in prepare_data_semi_supervised.py -> MHA2nnUNetConverter to:

output_dir: PathLike,
scans_dir: PathLike,
annotations_dir: Optional[PathLike] = None,
 mha2nnunet_settings

**Comment by Kyfafyd** [comment]
Hi @joeranbosma 
After finish `prepare_data_semi_supervised.py`, I meet another error when running `src/picai_baseline/unet/plan_overview.py`:
```
Traceback (most recent call last):
  File "src/picai_baseline/unet/plan_overview.py", line 51, in <module>
    lbl = sitk.GetArrayFromImage(sitk.ReadImage(str(preprocessed_data_path / 'labelsTr' / f'{subject_id}.nii.gz')))
  File "/research/d4/gds/zwang21/anaconda3/envs/surgical/lib/python3.8/site-packages/SimpleITK/extra.py", line 346, in ReadImage
    return reader.Execute()
  File "/research/d4/gds/zwang21/anaconda3/envs/surgical/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 8015, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "workdir/nnUNet_raw_data/Task2203_picai_baseline/labelsTr/11475_1001499.nii.gz" does not exist.
```

**Comment by Kyfafyd** [comment]
Any update? @joeranbosma Thanks!

**Comment by Kyfafyd** [comment]
Hi, @joeranbosma 
Thanks for your response!
So sorry I do not fully understand you! Regarding my current status, what should I do now?

**Comment by joeranbosma** [comment]
Hi @Kyfafyd,

The error you face results from resampling the annotation for case 1001499. Unfortunately, this is a limitation of the U-Net baseline method (the nnU-Net baseline does not have this issue, because nnU-Net uses a different resampling method). 
You can circumvent this resampling issue by using the automatically generated annotation, rather than the human expert annotation. To do so:

1. Remove the annotation for case 1001499 from `picai_labels/csPCa_lesion_delineations/combined/`
2. Add the code above to [`prepare_data_semi_supervised.py`](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/prepare_data_semi_supervised.py)
3. Run the script [`prepare_data_semi_supervised.py`](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/prepare_data_semi_supervised.py) again
4. The script `src/picai_baseline/unet/plan_overview.py` should run without issues now

**Comment by joeranbosma** [comment]
Hi @Kyfafyd,

I checked out the issue a bit more, unfortunately my proposed fix above does not work. Please follow [this thread](https://grand-challenge.org/forums/forum/pi-cai-607/topic/u-net-data-preprocessing-error-970/) for a solution.

Kind regards,
Joeran

**Comment by joeranbosma** [comment]
@Kyfafyd,

Have you been able to solve the issue with case 1001499?

I would like to inform you that we have implemented the option to use a regular for-loop over multithreading in our development branch: https://github.com/DIAGNijmegen/picai_prep/tree/refactor

Within this branch, you can set the number of threads to 1 to circumvent multiprocessing:

```python
from picai_prep import MHA2nnUNetConverter

archive = MHA2nnUNetConverter(
    input_path="/input/path/to/mha/archive",
    annotations_path="/input/path/to/annotations",  # defaults to input_path
    output_path="/output/path/to/nnUNet_raw_data",
    settings_path="/path/to/mha2nnunet_settings.json",
)
archive.settings.num_threads = 1
archive.convert()
```

Kind regards,
Joeran

**Comment by Kyfafyd** [comment]
Thanks for your update!
I will try this then!
